### ISSUE TITLE
spawn gatsby ENOENT

### ISSUE THREAD

**Issue by hongalLee** [baptisteArnaud/webflow-to-gatsby#10]
* **I'm submitting a ...**
[✅] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
unzipped webflow zip file and tried "npx webflow-to-gatsby ./webflow/ new-project" 
but returned "spawn gatsby ENOENT".

**Comment by baptisteArnaud** [comment]
Hi @hongalLee, you need to install Gatsby CLI before hand:
```
npm install -g gatsby-cli
```
I'll update the documentation right away

**Comment by FynnHunt** [comment]
I am having this same issue and I have gatsby-cli installed globally. I am in a directory with the exported and unzipped webflow site in a folder and running npx webflow-to-gatsby ./webflow-folder my-project 

I get no output other than "spawn gatsby ENOENT"

**Comment by baptisteArno** [comment]
What do you got if you run `gatsby -v` in your terminal?

**Comment by fkunecke** [comment]
Got the same issue. `spawn gatsby ENOENT` 
`Gatsby CLI version: 3.8.0`
`npx 6.14.8`
`node v14.15.1`
