### ISSUE TITLE
Webflow pages aren't building in src/pages

### ISSUE THREAD

**Issue by calrobertlee** [baptisteArnaud/webflow-to-gatsby#6]
None of the Webflow html pages are getting built as js pages in gatsby-project/src/pages

Everything else is building (CSS and images) correctly so I'm not sure what the issue is.

Thank you!!

**Comment by baptisteArnaud** [comment]
Hi @calrobertlee, for the moment, this plugin only accept Webflow project with a unique "index" page. [Here is the function that handles the index injection](https://github.com/baptisteArnaud/webflow-to-gatsby/blob/master/src/index.ts#L79).

I won't have time to work on this multi-page feature for now but feel free to contribute. :)

**Comment by calrobertlee** [comment]
Hi @baptisteArnaud thanks for getting back to me, I'll see what I can do.  Cheers!
