### ISSUE TITLE
Only getting the Hello world page

### ISSUE THREAD

**Issue by emanom** [baptisteArnaud/webflow-to-gatsby#8]
* **I'm submitting a ...**
[ ] question about how to use this project

* **Summary**
Only getting the Hello world page after running this and `gatsby develop`, is this project current?

**Comment by baptisteArnaud** [comment]
Hi @emanom ,

Could you give me a Webflow zip that reproduces this issue so that I can check what's wrong?

**Comment by ebarti** [comment]
Error when copying folders to gatsby project: Command failed: cp -r ./webflowf/images ./webflowf/css ./webflowf/fonts ./prj/src/
cp: ./webflowf/images: No such file or directory
cp: ./webflowf/css: No such file or directory
cp: ./webflowf/fonts: No such file or directory

Error when copying folders to gatsby project: cp: ./webflowf/images: No such file or directory
cp: ./webflowf/css: No such file or directory
cp: ./webflowf/fonts: No such file or directory

Copied resources.
(node:15967) UnhandledPromiseRejectionWarning: Command failed: cp -r ./webflowf/images ./webflowf/css ./webflowf/fonts ./prj/src/
cp: ./webflowf/images: No such file or directory
cp: ./webflowf/css: No such file or directory
cp: ./webflowf/fonts: No such file or directory

(Use `node --trace-warnings ...` to show where the warning was created)
(node:15967) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15967) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ebarti** [comment]
How can this ever work?

`cp -r ${webflowFolderPath}/images ${webflowFolderPath}/css ${webflowFolderPath}/fonts ./${gatsbyProjectName}/src/`,
      (error, stdout, stderr)`

` const { imageImports, imageVariables, html } = extractImageFiles(
    `${process.cwd()}/${webflowFolderPath}/index.html`
  );`

**Comment by baptisteArnaud** [comment]
@ebarti Are you sure you have a folder called "webflowf" ?

**Comment by baptisteArnaud** [comment]
Please feel free to reopen, if you still need help
