### ISSUE TITLE
🚨 Does not create Gatsby project from Webflow Zip 🚨

### ISSUE THREAD

**Issue by slightly-askew** [baptisteArnaud/webflow-to-gatsby#9]
* **I'm submitting a ...**
[ ✅] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Only generates a standard 'Hello World' gatsby project. Doesn't seem to do anything with the Webflow zip file.
The expectation was that it would turn my Webflow site into a (quick-n-dirty) gatsby website that I could deploy on a more performant host (minus all the js Webflow adds). 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by baptisteArnaud** [comment]
Hi @slightly-askew ,

You are supposed to unzip the webflow files first :

`npx webflow-to-gatsby <WEBFLOW_UNZIPPED_FOLDER> <GATSBY_PROJECT_NAME>`

Have you done this?
